from typing import Any, Iterable, Optional, Sequence
from _typeshed import Incomplete

__all__ = ['RemoteAPIClient']

class RemoteAPIClient:
    verbose: Incomplete
    context: Incomplete
    socket: Incomplete
    uuid: Incomplete
    callbackFuncs: Incomplete
    requiredItems: Incomplete
    VERSION: int
    timeout: Incomplete
    sendCnt: int
    def __init__(
        self,
        host: str = 'localhost',
        port: int = 23000,
        cntport: Optional[int] = None,
        *,
        verbose: Any = None,
    ) -> None: ...
    def __del__(self) -> None: ...
    def call(self, func: Any, args: Sequence[Any]) -> Any: ...
    def getObject(self, name: str, _info: Any | None = None) -> Any: ...
    def require(self, name: str) -> Any: ...
    def getScriptFunctions(self, scriptHandle: int) -> Any: ...
    def copyTable(self, table: Any) -> Any: ...
    def packUInt8Table(self, table: Sequence[int], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackUInt8Table(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def packUInt16Table(self, table: Sequence[int], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackUInt16Table(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def packUInt32Table(self, table: Sequence[int], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackUInt32Table(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def packInt32Table(self, table: Sequence[int], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackInt32Table(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def packFloatTable(self, table: Sequence[float], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackFloatTable(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def packDoubleTable(self, table: Sequence[float], start: int = 0, cnt: int = 0) -> Any: ...
    def unpackDoubleTable(self, data: Any, start: int = 0, cnt: int = 0, off: int = 0) -> Any: ...
    def setStepping(self, enable: bool = True) -> None: ...
    def step(self, *, wait: bool = True) -> None: ...
